### ISSUE TITLE
todo sections

### ISSUE THREAD

**Issue by furokku** [Flipnote-Collective/flipnote-studio-docs#4]
what's the status quo on the todo parts of pages?
is there no information about them, nobody willing to do them, or no time to do so?

**Comment by jaames** [comment]
nobody willing/interested in doing them, most people involved have since moved on to other things

**Comment by furokku** [comment]
I can offer to finish them, if possible, since I have a lot of interest in the 3rd party hatena server space and writing my own as a hobby project has provided me with a lot of insight. would that be alright?

**Comment by jaames** [comment]
by all means feel free :)
